<?php
session_start();
include('../mysql/db.php');
if (!isset($_SESSION['name'])) { header('Location: ../index.php'); exit(); }
if ($_SESSION['role'] !== 'superadmin') { header('Location: dashboard.php'); exit(); }

// Trigger backup download
if (isset($_GET['download'])) {
  $filename = 'coj_backup_' . date('Y-m-d_H-i-s') . '.sql';

  header('Content-Type: application/octet-stream');
  header('Content-Disposition: attachment; filename="' . $filename . '"');
  header('Pragma: no-cache');

  $tables = $conn->query("SHOW TABLES")->fetch_all(MYSQLI_NUM);

  echo "-- COJ Catholic Progressive School\n";
  echo "-- Database Backup: " . date('Y-m-d H:i:s') . "\n";
  echo "-- Generated by: " . htmlspecialchars($_SESSION['name']) . "\n\n";
  echo "SET FOREIGN_KEY_CHECKS=0;\n\n";

  foreach ($tables as $table) {
    $tname = $table[0];

    // Table structure
    $create = $conn->query("SHOW CREATE TABLE `$tname`")->fetch_assoc();
    echo "DROP TABLE IF EXISTS `$tname`;\n";
    echo $create['Create Table'] . ";\n\n";

    // Table data
    $rows = $conn->query("SELECT * FROM `$tname`");
    if ($rows && $rows->num_rows > 0) {
      while ($row = $rows->fetch_assoc()) {
        $values = array_map(function($v) use ($conn) {
          return $v === null ? 'NULL' : "'" . $conn->real_escape_string($v) . "'";
        }, array_values($row));
        echo "INSERT INTO `$tname` VALUES (" . implode(', ', $values) . ");\n";
      }
      echo "\n";
    }
  }

  echo "SET FOREIGN_KEY_CHECKS=1;\n";
  exit();
}

// Log the backup
$uid   = $_SESSION['user_id'] ?? 0;
$uname = $conn->real_escape_string($_SESSION['name'] ?? '');
$conn->query("INSERT INTO audit_log (user_id, user_name, action, target, details) VALUES ($uid, '$uname', 'database_backup', 'system', 'Manual backup downloaded')");

$active_page = 'backup';
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Database Backup</title>
  <link rel="icon" type="image/png" href="../images/COJ.png">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet"/>
  <link rel="stylesheet" href="../css/styles.css">
</head>
<body>
<?php include('includes/sidebar.php'); ?>
<div id="main">
  <div id="topbar">
    <div class="topbar-left">
      <div class="page-title">Database Backup</div>
      <div class="page-sub">Download a full backup of the school database</div>
    </div>
  </div>
  <div id="page-container">

    <div style="max-width:560px;">
      <div style="background:#fff;border:1px solid var(--color-border);border-radius:12px;padding:32px;">
        <div style="font-size:32px;color:var(--color-primary);margin-bottom:16px;"><i class="bi bi-database-fill-down"></i></div>
        <h2 style="font-size:18px;font-weight:700;margin-bottom:8px;">Download Database Backup</h2>
        <p style="font-size:13px;color:var(--color-muted);line-height:1.7;margin-bottom:24px;">
          This will download a complete SQL backup of the <strong>school_registrar</strong> database including all students, enrollments, payments, and documents.
          <br><br>
          Save the file to a USB drive or Google Drive for safekeeping.
        </p>

        <a href="backup.php?download=1"
           style="display:inline-flex;align-items:center;gap:8px;padding:11px 24px;background:var(--color-primary);color:#fff;border-radius:8px;font-size:14px;font-weight:600;text-decoration:none;">
          <i class="bi bi-download"></i> Download Backup (.sql)
        </a>
      </div>

      <div style="background:#fff;border:1px solid var(--color-border);border-radius:12px;padding:24px;margin-top:16px;">
        <div style="font-size:14px;font-weight:700;margin-bottom:12px;">How to restore a backup</div>
        <ol style="font-size:13px;color:var(--color-muted);line-height:2;padding-left:18px;">
          <li>Open <strong>phpMyAdmin</strong> (localhost/phpmyadmin)</li>
          <li>Select the <strong>school_registrar</strong> database</li>
          <li>Click the <strong>Import</strong> tab</li>
          <li>Choose the <strong>.sql</strong> backup file</li>
          <li>Click <strong>Import</strong></li>
        </ol>
      </div>

      <div style="background:#fef9c3;border:1px solid #fde68a;border-radius:8px;padding:14px 16px;margin-top:16px;font-size:13px;color:#92400e;">
        <strong>Recommended:</strong> Download a backup at the end of each enrollment day and store it in at least 2 locations (e.g. USB + Google Drive).
      </div>
    </div>

  </div>
</div>
<script src="../js/nav.js"></script>
</body>
</html>
